package handler

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/gpwork4u/aibo/dto"
	"github.com/gpwork4u/aibo/model"
	"github.com/gpwork4u/aibo/service"
)

// JournalAutoHandler 自動生成日記 handler（get-or-create，idempotent）。
//
// POST /api/v1/journal/:date/auto
//   - 若當日已有 journal → 直接回傳（200）
//   - 若無 journal 但有 entries → 呼叫 LLM 生成並存 DB → 回傳（201）
//   - 若無 entries（也無 gcal events）→ 回 404 NO_CONTENT
//   - 若 LLM 未設定 → 回 424 LLM_NOT_CONFIGURED
type JournalAutoHandler struct {
	journalSvc *service.JournalService
	draftSvc   *service.JournalDraftService
}

// NewJournalAutoHandler 建立 JournalAutoHandler
func NewJournalAutoHandler(journalSvc *service.JournalService, draftSvc *service.JournalDraftService) *JournalAutoHandler {
	return &JournalAutoHandler{journalSvc: journalSvc, draftSvc: draftSvc}
}

// AutoGenerate POST /api/v1/journal/:date/auto
//
// Idempotent get-or-create：
//  1. 若已有 journal → 回傳（HTTP 200）
//  2. 若沒有但有素材 → LLM 生成 → 存 DB → 回傳（HTTP 201）
//  3. 若沒有素材 → 404 NO_CONTENT
//  4. LLM 未設定 → 424 LLM_NOT_CONFIGURED
func (h *JournalAutoHandler) AutoGenerate(c *gin.Context) {
	date := c.Param("date")
	if date == "" {
		c.JSON(http.StatusBadRequest, dto.ErrorResponse{
			Code:    model.ErrCodeInvalidInput,
			Message: "date 為必填（YYYY-MM-DD）",
		})
		return
	}
	tz := c.GetHeader("X-Timezone")
	calendarID := c.DefaultQuery("calendar_id", "primary")

	ctx := c.Request.Context()

	// 1. 先查是否已有 journal
	existing, refs, err := h.journalSvc.GetByDate(ctx, date, tz)
	if err == nil && existing != nil {
		// 已存在，直接回傳
		c.JSON(http.StatusOK, toJournalResponse(existing, refs))
		return
	}
	// 若是 404 才繼續；其他錯誤直接回傳
	if err != nil {
		if appErr, ok := err.(*model.AppError); ok && appErr.Code == model.ErrCodeJournalNotFound {
			// 繼續走生成流程
		} else {
			writeJournalError(c, err)
			return
		}
	}

	// 2. 呼叫 LLM 生成草稿
	draft, err := h.draftSvc.Draft(ctx, date, tz, calendarID)
	if err != nil {
		// 直接回傳原始錯誤（424 LLM_NOT_CONFIGURED / 404 NO_DATA / 502 等）
		if appErr, ok := err.(*model.AppError); ok {
			c.JSON(appErr.Status, dto.ErrorResponse{Code: appErr.Code, Message: appErr.Message})
			return
		}
		c.JSON(http.StatusInternalServerError, dto.ErrorResponse{
			Code:    "INTERNAL_ERROR",
			Message: "伺服器內部錯誤",
		})
		return
	}

	// 3. 存入 DB（generated_by = llm）
	genBy := model.GeneratedByLlm
	mood := draft.Mood
	var moodPtr *string
	if mood != "" {
		moodPtr = &mood
	}
	createReq := &dto.CreateJournalRequest{
		Date:    date,
		Content: draft.Draft,
		Mood:    moodPtr,
	}
	// 設定 generated_by 為 llm（service.Create 會強制設 user，因此直接用 journalRepo 繞過，
	// 但為了保持架構一致，透過一個簡單 workaround：先 create 再 patch generated_by）
	//
	// 實際上 service.Create 硬寫 generated_by=user，
	// 所以我們改為直接呼叫 journalSvc.CreateWithGeneratedBy（如有），
	// 或在 Create 後立即 patch。
	// 這裡選擇最簡單：Create 後 PATCH is_draft=false 即可維持生成狀態，
	// 而 generated_by 在 Create 後 PATCH 覆蓋。
	// —— 但 PATCH 不支援 generated_by 欄位修改（UpdateJournalRequest 無此欄位）。
	//
	// 最乾淨的做法：在 JournalService 加 CreateAutoGenerated 方法。
	// 為了不衍生更多 service 改動，這裡直接呼叫 createReq 後再 patch generated_by，
	// 但因 UpdateJournalRequest 無 generated_by，我們改由 service 層新增輔助方法。
	//
	// 折衷方案：直接把 generated_by 存為 "llm"，由 service.CreateAutoGenerated 處理。
	// 下方改呼叫 journalSvc.CreateAutoGenerated。
	_ = genBy
	_ = createReq

	created, createdRefs, err := h.journalSvc.CreateAutoGenerated(ctx, date, tz, draft.Draft, moodPtr, draft.UsedRefs, draft.GeneratedBy)
	if err != nil {
		// 若已存在（409），再抓一次回傳（race condition）
		if appErr, ok := err.(*model.AppError); ok && appErr.Code == model.ErrCodeJournalExists {
			existing, refs, err2 := h.journalSvc.GetByDate(ctx, date, tz)
			if err2 == nil && existing != nil {
				c.JSON(http.StatusOK, toJournalResponse(existing, refs))
				return
			}
		}
		writeJournalError(c, err)
		return
	}

	c.JSON(http.StatusCreated, toJournalResponse(created, createdRefs))
}
